require 'rake'
require 'spec/rake/spectask'

desc "Run all examples"
Spec::Rake::SpecTask.new('examples') do |t|
  t.spec_files = FileList['specs/**/*.rb']
end

desc "Generate HTML report for examples"
Spec::Rake::SpecTask.new('examples_with_html') do |t|
  t.spec_files = FileList['specs/**/*.rb']
  t.spec_opts = ["--format", "html:reports/specification.html", "--diff"]
  t.fail_on_error = false
end
